.TH "GNOME-HEARTS" "6" 
.SH "NAME" 
gnome-hearts \(em play a game of hearts 
.SH "USAGE" 
.PP 
gnome-hearts [--show-cards]
.PP 
Gnome hearts is an implementation of the classic card game 
for the GNOME desktop, featuring configurable rulesets 
and editable computer opponents to satisfy widely 
diverging playing styles. 
.PP 
The full documentation is written in DocBook XML and
can be accessed through the GNOME help system.
.SH "OPTIONS"
.IP --show-cards
Show all the card faces when playing the game. Useful for debugging
your own AI players.
.SH "FILES"
.I $XDG_CONFIG_HOME/gnome-hearts/gnome-hearts.cfg
.RS
This file stores the configuration for gnome-hearts. It is automatically
created when you start the game for the first time. On most systems,
$XDG_CONFIG_HOME points to ~/.config
.SH "AUTHOR" 
.PP 
Gnome Hearts was written by Sander Marechal
 
.PP 
This manual page was written by Sander Marechal 
<s.marechal@jejik.com>.  Permission is granted to copy,
distribute and/or modify this document under the terms of the GNU 
Free Documentation License, Version 1.1 or any later 
version published by the Free Software Foundation; with no 
Invariant Sections, no Front-Cover Texts and no Back-Cover 
Texts. 
